### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by maoyj2333** [baaaad/ECE#1]
Congratulations on the paper accepted by ECCV, it is definitely an impressive work that well advance the SOTA of image captioning editing. I am wondering when the code will be released.

**Comment by baaaad** [comment]
收到

**Comment by baaaad** [comment]
Thank you for your interest and recognition of our work, we have now released the dataset and relevant contruction code. 

The code for model and training is coming soon.

**Comment by Gary-code** [comment]
Congratulations on the paper accepted by ECCV, I am wondering when the training source code will be released. Looking forward to your reply.

**Comment by baaaad** [comment]
Hi, the training source code is now avialable.
